### ISSUE TITLE
Send Notification to all users at once ?

### ISSUE THREAD

**Issue by rabeeaali** [ankurk91/fcm-notification-channel#5]
Is there any way to send a Notification to all tokens at once? 

I use this way:

```
Notification::route('FCM', $usersTokens)
         ->route('FCMTargetType', MessageTarget::TOKEN)
        ->notify(new SendFCMNotification($this->notification));
```

But it throws `App\Notifications\SendFCMNotification has been attempted too many times.` cuz i have 22k tokens

even I increase the timeout of the job but still get this error

**Comment by ankurk91** [comment]
You should send them in chunks.
I can not teach you scaling here on GitHub.

**Comment by rabeeaali** [comment]
OK chunks in how many numbers in each chunk?
