### ISSUE TITLE
Migrating from benwilkins/laravel-fcm-notification package?

### ISSUE THREAD

**Issue by ivanhoe011** [ankurk91/fcm-notification-channel#8]
**I'm submitting a ...**  (check one with "x")

```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[X] Other, please describe
```

**Tell about your platform**

* Laravel version : 10.x
* php version : 8.1

I'm looking to replace benwilkins/laravel-fcm-notification package in an old project now being upgraded to Laravel 10. I've ran into your comment there (https://github.com/benwilkins/laravel-fcm-notification/issues/76#issuecomment-1378905138) which links to this package. However, it's not clear from the comment if this is in-place replacement for benwilkins/laravel-fcm-notification or I'll need to refactor my code? 

It would be a great time-saver if you could tell me what, or at least how many, changes are needed to migrate code to your package (and perhaps you could add that info to the README too)?

**Comment by ankurk91** [comment]
Please read the documentation

**Comment by circuitmamu** [comment]
I'm using
use NotificationChannels\Fcm\FcmChannel;

my when queu rund it will pick
use NotificationChannels\FCM\FCMChannel;

I'm using both packages
```
"ankurk91/fcm-notification-channel": "^2.1",
"laravel-notification-channels/fcm": "^4.3",
```

**So any idea where the issue or problem is?**
